version: "3.9"

services:
  bot:
    restart: always
    build: .
    volumes:
      - .:/mono_card_balance
    env_file: .env
    depends_on:
      - mongo
    command: >
      sh -c "python3 main.py"

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb: